### ISSUE TITLE
Contribute this to mainline GNU Emacs

### ISSUE THREAD

**Issue by skangas** [thierryvolpiatto/pcomplete-extension#2]
Please consider contributing this code for inclusion in mainline GNU Emacs.

I think it has general appeal and if it was available by default all Emacs users could benefit.  If you would like to do so, you could send an email to bug-gnu-emacs@gnu.org declaring your intention to contribute it.  If I'm not mistaken, you already have a copyright assignment to the Free Software Foundation?

Thanks in advance for considering this request, and for the useful package.

**Comment by thierryvolpiatto** [comment]
Stefan Kangas <notifications@github.com> writes:

> Please consider contributing this code for inclusion in mainline GNU Emacs.
>
> I think it has general appeal and if it was available by default all
> Emacs users could benefit. If you would like to do so, you could send
> an email to bug-gnu-emacs@gnu.org declaring your intention to
> contribute it.

Thanks for your interest of some of my packages and the proposition, but
I don't contribute anymore directly to Emacs.

> If I'm not mistaken, you already have a copyright assignment to the
> Free Software Foundation?

Yes.


-- 
Thierry

**Comment by skangas** [comment]
> Thanks for your interest of some of my packages and the proposition, but I don't contribute anymore directly to Emacs.

Thank you for your reply. Is it impolite to ask the reasons why? Is there anything that could be done to make you more willing to contribute directly to Emacs?

**Comment by thierryvolpiatto** [comment]
Stefan Kangas <notifications@github.com> writes:

>     Thanks for your interest of some of my packages and the
>     proposition, but I don't contribute anymore directly to Emacs.
>    
> Thank you for your reply. Is it impolite to ask the reasons why?

Too much disagreements with some Emacs maintainers.

> Is there anything that could be done to make you more willing to
> contribute directly to Emacs?

No, but thanks for the offer.


-- 
Thierry

**Comment by skangas** [comment]
OK, thanks for considering the proposal.
